# -*- coding: utf-8 -*-
"""Codegen_fine_tuning_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vpu-89baDQJ56oxkkm6gqvWTE1UPr_m7

#Import Libraries
"""

!pip install -q transformers datasets
!pip install -q accelerate -U
!pip install -q gdown
!pip install --upgrade jax transformers
!pip install --upgrade packaging==21.0
!pip install --upgrade torch==2.2.2
!pip install --upgrade jaxlib==0.4.20
!pip install --upgrade jax transformers
!pip install trl

!pip install -q streamlit                                                          # For Deploying apps
!pip install -q transformers>=4.32.0 datasets evaluate
!pip install -q auto-gptq
!pip install -q optimum                                                           # For GPTQ Optimization
!pip install -q -U bitsandbytes                                                    # For quantization
!pip install git+https://github.com/huggingface/peft.git
!pip install -q -U accelerate                                                                         # Loading models across GPUs/CPU/disk
!pip install -q trl                                                                          # For supervised fine-tuning for LLMs
!pip install git+https://github.com/k4black/codebleu.git                                               #CodeBLEU

!pip install --upgrade peft

!pip install --upgrade trl

"""#Load the dataset"""

from datasets import Dataset,load_dataset

# Load the dataset using the load_dataset function
data = load_dataset("iamtarun/python_code_instructions_18k_alpaca")

"""#Formatting dataset"""

def formatting_func(example):

    instruction = example['instruction'][0]
    output = example['output'][0]


    text = f"<start_of_turn>user\n{instruction}<end_of_turn> <start_of_turn>model\n{output}<end_of_turn>"

    return [text]

"""#Splitting"""

from datasets import DatasetDict
subset_data = DatasetDict({"train": data['train'].select(range(200)).remove_columns(['input', 'prompt'])})
test_dataset = DatasetDict({"test": data['train'].select(range(300,400)).remove_columns(['input', 'prompt'])})

print(subset_data)

print(test_dataset)

from codebleu import calc_codebleu
def generate_predictions_and_evaluate(model, tokenizer, test_dataset, max_length=200):
    predictions = []
    references = []

    for example in test_dataset['test']:
        input_text = example['instruction']


        chunks = [input_text[i:i+max_length] for i in range(0, len(input_text), max_length)]

        # Generate predictions for each chunk
        generated_texts = []
        for chunk in chunks:
            inputs = tokenizer(chunk, return_tensors="pt", truncation=True, padding=True)
            output_ids = model.generate(**inputs, max_length=max_length)
            generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
            generated_texts.append(generated_text)

        # Concatenate the generated chunks to form the complete sequence
        generated_text = ' '.join(generated_texts)

        reference_text = example['output']

        predictions.append(generated_text)
        references.append(reference_text)

    # Calculate CodeBLEU score
    codebleu_score = calc_codebleu(references, predictions, lang="python", tokenizer=None)

    return codebleu_score

"""#Model A"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import BitsAndBytesConfig
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,                     # Q = 4 bits
    bnb_4bit_use_double_quant=True,        # double quantization, quantizing the quantization constants for saving an additional 0.4 bits per parameter
    bnb_4bit_quant_type="nf4",             # 4-bit NormalFloat Quantization (optimal for normal weights; enforces w ∈ [-1,1])
    bnb_4bit_compute_dtype=torch.bfloat16  # Dequantize to 16-bits before computations (as in the paper)
)
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-2B-mono")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-2B-mono", quantization_config=bnb_config, device_map="auto")

print(model)

tokenizer.pad_token = tokenizer.eos_token

"""#Model A evaluation"""

codebleu_score_model_A = generate_predictions_and_evaluate(model,tokenizer , test_dataset)

print("CodeBLEU ScoreA:", codebleu_score_model_A)

from google.colab import drive
drive.mount('/content/drive')

import os


directory = '/content/drive/MyDrive/checkpoints/'


if not os.path.exists(directory):
    os.makedirs(directory)


file_path = os.path.join(directory, 'codebleu_scoreA.txt')


with open(file_path, 'w') as f:
    f.write(str(codebleu_score_model_A))

import os
import ast

file_path = '/content/drive/MyDrive/checkpoints/codebleu_scoreA.txt'


if os.path.exists(file_path):

    with open(file_path, 'r') as f:
        codebleu_score_model_A = f.read()
    codebleu_score_model_A = ast.literal_eval(codebleu_score_model_A)

    print("CodeBLEU score of Model A:", codebleu_score_model_A)
else:
    print("File does not exist.")

"""#Model B"""

from peft import LoraConfig

# Configure LoraConfig for model pruning
lora_config = LoraConfig(
    r=8,
    target_modules=["qkv_proj", "out_proj"],
    task_type="CAUSAL_LM",
)

import transformers
from trl import SFTTrainer

# Initialize the SFTTrainer
trainer = SFTTrainer(
    model=model,
    train_dataset=subset_data['train'],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        warmup_steps=2,
        max_steps=5,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=3,
        output_dir="outputs",
        optim="paged_adamw_8bit"
    ),
    peft_config=lora_config,
    formatting_func=formatting_func,
)

#200
trainer.train()

peft_model_path ="./fine-tuned-modelb-codegen"
trainer.model.save_pretrained(peft_model_path)
tokenizer.save_pretrained(peft_model_path)

from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer
tuned_model_b = AutoPeftModelForCausalLM.from_pretrained(peft_model_path, low_cpu_mem_usage=True, torch_dtype=torch.float16, load_in_4bit=True)
tokenizer_b = AutoTokenizer.from_pretrained(peft_model_path)

inputs = tokenizer("#function to see the the email is valid or no ", return_tensors="pt")
sample = model.generate(**inputs, max_length=128)
print(tokenizer_b.decode(sample[0], truncate_before_pattern=[r"\n\n^#", "^'''", "\n\n\n"]))

inputs = tokenizer_b("#function to see the the email is valid or not ", return_tensors="pt")
sample = tuned_model_b.generate(**inputs, max_length=200)
print(tokenizer_b.decode(sample[0], truncate_before_pattern=[r"\n\n^#", "^'''", "\n\n\n"]))

"""#Model B evalaution"""

codebleu_score_model_B = generate_predictions_and_evaluate(tuned_model_b,tokenizer_b , test_dataset)

print("CodeBLEU ScoreB:", codebleu_score_model_B)

import os


directory = '/content/drive/MyDrive/checkpoints/'


if not os.path.exists(directory):
    os.makedirs(directory)


file_path = os.path.join(directory, 'codebleu_scoreB.txt')


with open(file_path, 'w') as f:
    f.write(str(codebleu_score_model_B))

import os
import ast

file_path = '/content/drive/MyDrive/checkpoints/codebleu_scoreB.txt'


if os.path.exists(file_path):

    with open(file_path, 'r') as f:
        codebleu_score_model_B = f.read()

    codebleu_score_model_B = ast.literal_eval(codebleu_score_model_B)

    print("CodeBLEU score of Model B:",codebleu_score_model_B)
else:
    print("File does not exist.")

"""#Model C"""

from datasets import Dataset, DatasetDict
import pandas as pd


df = pd.read_csv("/content/first_600 csv.csv")

# Convert DataFrame to DatasetDict
dataset_dict_train_c = DatasetDict({
    "train": Dataset.from_pandas(df).rename_column("Instruction", "instruction")
                                     .rename_column("Code", "output")
})


print(dataset_dict_train_c)

from peft import LoraConfig


lora_config = LoraConfig(
    r=8,
    target_modules=["qkv_proj", "out_proj"],
    task_type="CAUSAL_LM",
)

import transformers
from trl import SFTTrainer

# Initialize the SFTTrainer
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset_dict_train_c['train'],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        warmup_steps=2,
        max_steps=5,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=5,
        output_dir="outputs",
        optim="paged_adamw_8bit"
    ),
    peft_config=lora_config,
    formatting_func=formatting_func,
)

trainer.train()

peft_model_path2 ="./fine-tuned-modelC-codegen"
trainer.model.save_pretrained(peft_model_path2)
tokenizer.save_pretrained(peft_model_path2)

from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer
tuned_model_c = AutoPeftModelForCausalLM.from_pretrained(peft_model_path2, low_cpu_mem_usage=True, torch_dtype=torch.float16, load_in_4bit=True)
tokenizer_c = AutoTokenizer.from_pretrained(peft_model_path2)

"""#Evalaution of Model C"""

codebleu_score_model_C = generate_predictions_and_evaluate(tuned_model_c, tokenizer_c,test_dataset)

print("CodeBLEU ScoreC:", codebleu_score_model_C)

import os
import ast

directory = '/content/drive/MyDrive/checkpoints/'


if not os.path.exists(directory):
    os.makedirs(directory)


file_path = os.path.join(directory, 'codebleu_scoreC.txt')


with open(file_path, 'w') as f:
    f.write(str(codebleu_score_model_C))

import os
import ast

file_path = '/content/drive/MyDrive/checkpoints/codebleu_scoreC.txt'


if os.path.exists(file_path):

    with open(file_path, 'r') as f:
        codebleu_score_model_C = f.read()
    codebleu_score_model_C = ast.literal_eval(codebleu_score_model_C)

    print("CodeBLEU score of Model C:",codebleu_score_model_C)
else:
    print("File does not exist.")

"""#Model D"""

from datasets import concatenate_datasets
import numpy as np

# Combine the datasets
combined_data = concatenate_datasets([subset_data['train'], dataset_dict_train_c['train']])


np.random.seed(42)
combined_data = combined_data.shuffle(seed=42)

print(combined_data)

train_data_D = DatasetDict({"train" : combined_data})

print(train_data_D)

import pandas as pd

combined_df = combined_data.to_pandas()

csv_file_path = "combined_data.csv"


combined_df.to_csv(csv_file_path, index=False)

print("Combined dataset has been written to", csv_file_path)

from peft import LoraConfig

# Configure LoraConfig for model pruning
lora_config = LoraConfig(
    r=8,
    target_modules=["qkv_proj", "out_proj"],
    task_type="CAUSAL_LM",
)

import transformers
from trl import SFTTrainer

# Initialize the SFTTrainer
trainer = SFTTrainer(
    model=model,
    train_dataset=train_data_D['train'],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        warmup_steps=2,
        max_steps=5,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=3,
        output_dir="outputs",
        optim="paged_adamw_8bit"
    ),
    peft_config=lora_config,
    formatting_func=formatting_func,
)

trainer.train()

peft_model_path ="./fine-tuned-modelD-codegen"
trainer.model.save_pretrained(peft_model_path)
tokenizer.save_pretrained(peft_model_path)

from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer
tuned_model_d = AutoPeftModelForCausalLM.from_pretrained(peft_model_path, low_cpu_mem_usage=True, torch_dtype=torch.float16, load_in_4bit=True)
tokenizer_d = AutoTokenizer.from_pretrained(peft_model_path)

"""#Evalaution of Model D"""

#200+600=800
codebleu_score_model_D = generate_predictions_and_evaluate(tuned_model_d, tokenizer_d,test_dataset)

#200+600=800
print(codebleu_score_model_D )

import os


directory = '/content/drive/MyDrive/checkpoints/'


if not os.path.exists(directory):
    os.makedirs(directory)


file_path = os.path.join(directory, 'codebleu_scoreD.txt')

# Saving the CodeBLEU score to a file
with open(file_path, 'w') as f:
    f.write(str(codebleu_score_model_D))

import os
import ast

file_path = '/content/drive/MyDrive/checkpoints/codebleu_scoreD.txt'


if os.path.exists(file_path):

    with open(file_path, 'r') as f:
        codebleu_score_model_D = f.read()

    codebleu_score_model_D = ast.literal_eval(codebleu_score_model_D)
    # Print the value
    print("CodeBLEU score of Model D:",codebleu_score_model_D)
else:
    print("File does not exist.")

"""#Visualization"""

print(codebleu_score_model_A)
print(codebleu_score_model_B)
print(codebleu_score_model_C)
print(codebleu_score_model_D)

model_A_codeblue_score = codebleu_score_model_A['codebleu']
model_B_codeblue_score = codebleu_score_model_B['codebleu']
model_C_codeblue_score = codebleu_score_model_C['codebleu']
model_D_codeblue_score = codebleu_score_model_D['codebleu']

model_A_dataflow_match_score = codebleu_score_model_A['dataflow_match_score']
model_B_dataflow_match_score= codebleu_score_model_B['dataflow_match_score']
model_C_dataflow_match_score = codebleu_score_model_C['dataflow_match_score']
model_D_dataflow_match_score = codebleu_score_model_D['dataflow_match_score']

model_A_weighted_ngram_match_score = codebleu_score_model_A['weighted_ngram_match_score']
model_B_weighted_ngram_match_score = codebleu_score_model_B['weighted_ngram_match_score']
model_C_weighted_ngram_match_score = codebleu_score_model_C['weighted_ngram_match_score']
model_D_weighted_ngram_match_score = codebleu_score_model_D['weighted_ngram_match_score']

model_A_syntax_match_score = codebleu_score_model_A['syntax_match_score']
model_B_syntax_match_score = codebleu_score_model_B['syntax_match_score']
model_C_syntax_match_score = codebleu_score_model_C['syntax_match_score']
model_D_syntax_match_score = codebleu_score_model_D['syntax_match_score']

model_A_ngram_match_score = codebleu_score_model_A['ngram_match_score']
model_B_ngram_match_score = codebleu_score_model_B['ngram_match_score']
model_C_ngram_match_score = codebleu_score_model_C['ngram_match_score']
model_D_ngram_match_score = codebleu_score_model_D['ngram_match_score']

import matplotlib.pyplot as plt

# Data for plotting
codebleu_scores = [model_A_codeblue_score,model_B_codeblue_score,model_C_codeblue_score,model_D_codeblue_score]
models = ['Model A', 'Model B', 'Model C', 'Model D']

# Plotting
plt.figure(figsize=(10, 6))
plt.bar(models, codebleu_scores, color='skyblue')


plt.ylim(min(codebleu_scores) - 0.005, max(codebleu_scores) + 0.005)

# Adding labels and title
plt.title('CodeBLEU Scores of Different Models')
plt.xlabel('Models')
plt.ylabel('CodeBLEU Score')
plt.grid(axis='y')

# Annotating bars with values
#for i, score in enumerate(codebleu_scores):
#    plt.text(i, score, f"{score:.4f}", ha='center', va='bottom')

# Display plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data for plotting
codebleu_scores = [model_A_codeblue_score, model_B_codeblue_score, model_C_codeblue_score, model_D_codeblue_score]
ngram_match_scores = [model_A_ngram_match_score, model_B_ngram_match_score, model_C_ngram_match_score, model_D_ngram_match_score]
weighted_ngram_scores = [model_A_weighted_ngram_match_score , model_B_weighted_ngram_match_score , model_C_weighted_ngram_match_score , model_D_weighted_ngram_match_score ]
syntax_match_scores = [model_A_syntax_match_score, model_B_syntax_match_score, model_C_syntax_match_score, model_D_syntax_match_score]
dataflow_match_scores = [model_A_dataflow_match_score, model_B_dataflow_match_score, model_C_dataflow_match_score, model_D_dataflow_match_score]
models = ['Model A', 'Model B', 'Model C', 'Model D']

# Plotting
fig, axes = plt.subplots(5, 1, figsize=(10, 20))

# CodeBLEU Scores
axes[0].bar(models, codebleu_scores, color='skyblue')
axes[0].set_title('CodeBLEU Scores')
axes[0].set_ylabel('Score')
axes[0].set_ylim(min(codebleu_scores) - 0.005, max(codebleu_scores) + 0.005)

# Ngram Match Scores
axes[1].bar(models, ngram_match_scores, color='lightgreen')
axes[1].set_title('Ngram Match Scores')
axes[1].set_ylabel('Score')
axes[1].set_ylim(min(ngram_match_scores) - 0.005, max(ngram_match_scores) + 0.005)

# Weighted Ngram Match Scores
axes[2].bar(models, weighted_ngram_scores, color='orange')
axes[2].set_title('Weighted Ngram Match Scores')
axes[2].set_ylabel('Score')
axes[2].set_ylim(min(weighted_ngram_scores) - 0.005, max(weighted_ngram_scores) + 0.005)

# Syntax Match Scores
axes[3].bar(models, syntax_match_scores, color='lightcoral')
axes[3].set_title('Syntax Match Scores')
axes[3].set_ylabel('Score')
axes[3].set_ylim(min(syntax_match_scores) - 0.005, max(syntax_match_scores) + 0.005)

# Dataflow Match Scores
axes[4].bar(models, dataflow_match_scores, color='violet')
axes[4].set_title('Dataflow Match Scores')
axes[4].set_ylabel('Score')
axes[4].set_ylim(min(dataflow_match_scores) - 0.005, max(dataflow_match_scores) + 0.005)

# Adjust layout
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data for plotting
model = ['A', 'B', 'C', 'D']
codebleu_scores = [model_A_score,model_B_score,model_C_score,model_D_score]

# Plotting
plt.figure(figsize=(8, 5))
plt.plot(model, codebleu_scores, marker='o', color='blue', linestyle='-')

# Adding labels and title
plt.title('CodeBLEU Scores Across Model')
plt.xlabel('Models')
plt.ylabel('CodeBLEU Score')
plt.grid(True)


# Annotating points with values
for i, score in enumerate(codebleu_scores):
    plt.annotate(f"{score:.4f}", (model[i], score), textcoords="offset points", xytext=(0,10), ha='center')

# Display plot
plt.tight_layout()
plt.show()

"""#STREAMLIT"""

app_file_str = """
model = {tuned_model_d
tokenizer = """+"\""+tokenizer_d+"\""+"""
import streamlit as st
import requests
import json

def generate_code(instruction,model,tokenizer):
    inputs = tokenizer(instruction, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(**inputs, max_length=128, pad_token_id=tokenizer.eos_token_id)
    return tokenizer.decode(output[0])

def get_user_prompt():
    # simple title for the page
    st.title("Assistant to generate code")
    # take user input
    user_input = st.text_input("Enter the instruction for which you want python code.", key="input1")
    # button to ask finetuned codegen
    if st.button("Send", key="button1"):
        if user_input:
            # send to backend
            return generate_code(user_input, model, tokenizer)
        else:
            # if user clicks the button without text in the input box
            return "Please Enter Some Text"

# string output as a markdown
def show(output):
    if output:
        st.markdown(output)

# main function to wrap everything in one tab
def main():
    output = get_user_prompt()
    show(output)

if _name_ == "_main_":
    main()
"""

with open("app.py", 'w') as file:
    # Write the code content to the file
    file.write(app_file_str)

!npm install --silent localtunnel

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501 --subdomain mysubdomain --timeout 300000

!npx localtunnel --port 8501 & curl ipv4.icanhazip.com